version: "3.4"

services:

  synapse-db:
    image: postgres:13-bullseye
    volumes:
      - ./synapse-db:/var/lib/postgresql/data
      - ./synapse-ref/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./lemon/init-llng-db.sh:/docker-entrypoint-initdb.d/init-llng-db.sh
      - ./lemon/lmConf-1.json:/llng-conf/conf.json
    environment:
      - POSTGRES_PASSWORD=synapse!!
    healthcheck:
      test: "exit 0"

  redis:
    image: redis

  synapse:
    image: matrixdotorg/synapse
    container_name: synapse
    hostname: matrix.example.com
    volumes:
      - ./synapse-data:/data
      - ./ssl/ca-cert.pem:/etc/ssl/certs/ca-cert.pem
      - ./ssl/9da13359.0:/etc/ssl/certs/9da13359.0
    depends_on: 
      auth:
        condition: service_started

  auth:
    image: yadd/lemonldap-ng-dev
    container_name: auth
    hostname: auth.example.com
    volumes:
      - ./lemon/matrix-vhost.conf:/etc/nginx/sites-enabled/matrix.conf
      - ./lemon/ssl.conf:/etc/nginx/sites-enabled/0000default.conf
      - ./fluffychat:/var/www/fluffychat
      - ./lemon/fluffychat.conf:/etc/nginx/sites-enabled/fluffychat.conf
      - ./ssl:/etc/nginx/ssl
    environment:
      - SSODOMAIN=example.com
      - PORTAL=https://auth.example.com
      - LOGLEVEL=debug
      - LOGGER=stderr
      - USERLOGGER=stderr
      - PG_SERVER=synapse-db
      - REDIS_SERVER=redis:6379
    depends_on: 
      synapse-db:
        condition: service_healthy

  manager:
    image: yadd/lemonldap-ng-manager
    environment:
      - PG_SERVER=db
      - REDIS_SERVER=redis:6379
      - LOGGER=stderr
      - USERLOGGER=stderr
    depends_on:
      synapse-db:
        condition: service_healthy
      redis:
        condition: service_started

  haproxy:
    image: haproxy:2.6-bullseye
    ports:
      - 443:443
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
      - ./ssl/both.pem:/etc/ssl/certs/both.pem
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    depends_on:
      - auth
      - manager
      - synapse
