version: "3.4"

services:

  synapse-db:
    image: postgres:13-bullseye
    volumes:
      - ./synapse-db:/var/lib/postgresql/data
      - ./synapse-ref/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      - ./lemon/init-llng-db.sh:/docker-entrypoint-initdb.d/init-llng-db.sh
      - ./lemon/lmConf-1.json:/llng-conf/conf.json
    environment:
      - POSTGRES_PASSWORD=synapse!!
    healthcheck:
      test: "exit 0"
    networks:
      - db

  redis:
    image: redis
    networks:
      - sso

  synapse:
    image: matrixdotorg/synapse
    hostname: matrix.example.com
    volumes:
      - ./synapse-data:/data
      - ./ssl/ca-cert.pem:/etc/ssl/certs/ca-cert.pem
      - ./ssl/9da13359.0:/etc/ssl/certs/9da13359.0
    depends_on: 
      auth:
        condition: service_started
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr
      restart_policy:
        condition: on-failure
        delay: 5s
        window: 120s
    networks:
      - db
      - frontend

  auth:
    image: yadd/lemonldap-ng-portal
    hostname: auth.example.com
    volumes:
      - ./lemon/matrix-vhost.conf:/etc/nginx/sites-enabled/matrix.conf
      - ./lemon/ssl.conf:/etc/nginx/sites-enabled/0000default.conf
      - ./fluffychat:/var/www/fluffychat
      - ./lemon/fluffychat.conf:/etc/nginx/sites-enabled/fluffychat.conf
      - ./ssl:/etc/nginx/ssl
    environment:
      - SSODOMAIN=example.com
      - PORTAL=https://auth.example.com
      - LOGLEVEL=notice
      - LOGGER=stderr
      - USERLOGGER=stderr
      - PG_SERVER=synapse-db
      - REDIS_SERVER=redis:6379
    depends_on: 
      synapse-db:
        condition: service_healthy
    scale: 3
    networks:
      - db
      - frontend
      - sso

  manager:
    image: yadd/lemonldap-ng-manager
    environment:
      - SSODOMAIN=example.com
      - PORTAL=https://auth.example.com
      - PG_SERVER=synapse-db
      - REDIS_SERVER=redis:6379
      - LOGLEVEL=notice
      - LOGGER=stderr
      - USERLOGGER=stderr
    depends_on:
      synapse-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - db
      - frontend
      - sso

  haproxy:
    image: haproxy:2.6-bullseye
    ports:
      - 443:443
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
      - ./ssl/both.pem:/etc/ssl/certs/both.pem
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    environment:
      - COMPOSE_PROJECT_NAME
    depends_on:
      - auth
      - manager
      - synapse
    networks:
      - frontend

networks:
  db:
    name: db
  sso:
    name: sso
  frontend:
    name: frontend
